### ISSUE TITLE
rendering is split into strips

### ISSUE THREAD

**Issue by emko** [twinaphex/mame-old#3] opened 2016-06-14 04:37 UTC
was using mame 2014 for a while now just grabbed mame 174 core and all my games render with what looks like maybe 15 vertical strips where the image is not aligned.

I managed to find out this setting causes it on libretro mame

unevenstretch             1

setting it to 0 fixed is the problem, the thing is on non libretto mame this setting does not cause the same problem. 

I am running windows 10 and nvidia gpu

**Comment by Enverex** [comment] 2016-07-14 12:21
I'll try and get some pictures/video of this later to clarify the problem.

Unfortunately it makes the Mame core pretty much unusable right now because it looks *really* bad.

**Comment by Trevor-Z** [comment] 2016-07-17 13:53
Happens on OSX, too. The games are not being scaled properly horizontally (hence the vertical strips). It's weird, because otherwise, in the details of the image and the vertical axis, the bilinear filtering is working normally.

**Comment by Dagnillo** [comment] 2016-08-12 13:46
I noticed this as well.  Enabling alternate render method seems to fix it but then shaders aren't being used by the core.  Perhaps it's tied to the resolution issue?

**Comment by Awakened0** [comment] 2016-09-18 20:38
Here are screenshot comparisons.

unevenstretch 1 (default):
![image](https://cloud.githubusercontent.com/assets/4565863/18618883/cc8ceb7e-7dbd-11e6-9b0e-73879119d512.png)

unevenstretch 0:
![image](https://cloud.githubusercontent.com/assets/4565863/18618891/ebb47242-7dbd-11e6-9773-8a0b9c8be9fb.png)

Setting it to 0 fixes the missing pixels, but the aspect ratio still isn't right (set to Core Provided should be 4:3 for CPS2 games). And the OSD is still unreadable.

I was looking at the 0.172 changelog and noticed changes in unevenstretch and the OSD font API. That may have been what broke things in the core.

**Comment by r-type** [comment] 2016-10-27 13:39
i try to look at the issue but par/dar/aspect/pixel aspect are above of me!
here what i get using a libretro mame (black border but aspect seem correct)
and the other img is official mame (using wine)

![sfa2_retro2mame](https://cloud.githubusercontent.com/assets/3614417/19769315/36323a8c-9c5b-11e6-9690-262929686a99.png)

**Comment by Awakened0** [comment] 2016-10-27 22:15
Well, I get DAR (4:3) when I select 1:1 PAR (12:7 DAR) as the aspect ratio index in RetroArch with the Win64 mame_libretro.dll nightly from the buildbot (based on 0.174):
![image](https://cloud.githubusercontent.com/assets/4565863/19787180/626ab250-9c6f-11e6-8683-4f4a6444032a.png)

When I select Core Provided, which should give me DAR (4:3), I get some weird squished aspect:
![image](https://cloud.githubusercontent.com/assets/4565863/19787204/87be6150-9c6f-11e6-9393-2759b35aa3f1.png)

So 1:1 is giving my the opposite of what it should, and Core Provided is giving me something weird. @fr500 said something about needing to change how libretro calculates the aspect ratio, but he couldn't get the MAME core to compile with his setup to work on it.

Here's how MAME 2015 displays Core Provided:
![image](https://cloud.githubusercontent.com/assets/4565863/19787369/4f87ec38-9c70-11e6-9899-ae0aab396c34.png)

And 1:1 PAR (12:7 DAR):
![image](https://cloud.githubusercontent.com/assets/4565863/19787380/60a79c16-9c70-11e6-9002-179baa379fd6.png)

Those match with the Standard (4:3) and Pixel Aspect (12:7) options in standalone MAME.

**Comment by r-type** [comment] 2016-10-28 00:20
I have build a win64 test version (not based of libretro fork , so WIP buggy and less functional)
but could you please try it to see if it has the same behaviour and report?

 http://dl.free.fr/n0308YhiJ

on my linux side, the aspect seem correct but i give me black border if i scale at X2 like in previous img.

**Comment by Awakened0** [comment] 2016-10-28 02:23
With your build, I get 4:3 aspect in both Core Provided and 1:1 PAR aspect ratio indexes. Your build seems to be using the alternate renderer even when I have that option off though, since it makes CRT shaders look bad. If I enable the alternate renderer in the 0.174 core from the buildbot, I get proper 12:7 for 1:1 PAR and 4:3 for Core Provided.

**Comment by r-type** [comment] 2016-10-28 13:06
thanks for testing and report, 

yes in this debug build i use alternate renderer set to 640x480 , and that is a part of the problem.
the core option alternate_renderer have no effect in this test build.

if 640x480 would fit for 4:3 it will mess with 1:1 because it resize it to fit in a 640x480 view.

i'm not sure to know how deal it correctly , with the recent mame osd view change.

to resume (to me) ,

- OSD font looks bad if we are not using alternate renderer (ui_aspect ?)  
- if we are using alternate renderer with fixed resolution it will mess to get correct aspect
depending the layout_view eg: in sfa2 640x480 is correct for 4:3 but not for 12:7.
- if we are not using alternate renderer , it will mess to get correct aspect. (why?)

**Comment by Enverex** [comment] 2016-10-28 13:08
Would it be worth rebasing to current MAME before trying to fix this in case they've changed things further and a fix for the current state wouldn't work with upstream's current setup? (having to do it all over again)

**Comment by r-type** [comment] 2016-10-28 13:23
my current fork is 0.179 based.
it why i try to fix it now using my fork.then we could re-base here after a solution came for correct aspect.

**Comment by Enverex** [comment] 2016-10-28 13:32
One step ahead I see.

**Comment by r-type** [comment] 2016-10-28 22:04
@Awakened0 could you try another one , 
it's an non alternate renderer version (so the font mess up in UI)

http://dl.free.fr/rLuaRnhcL

**Comment by Awakened0** [comment] 2016-10-28 22:28
That build fixes the aspect ratio issues in the non-alternate renderer. Both 1:1 PAR and Core Provided work like they should (same as my MAME 2015 screenshots). Nice work!

I have to keep remembering to turn off the no-nag options when I try your builds since they crash when enabled :P

**Comment by r-type** [comment] 2016-10-28 23:37
nice if it solve the aspect problem . but then it break osd font (too small resolution ? ui-aspect?)
I would have liked to use a fixed resolution (better font/overlay rendering) .
it's a WIP test fork so all is not working like this one.
later i will look at all other things i have omitted like no-nag option !

**Comment by Awakened0** [comment] 2016-10-29 00:17
Maybe the OSD problem in the normal renderer is like what happened with the new hybrid mode in the desmume core: https://github.com/libretro/desmume/pull/90

The smaller copies of the screen get pixellated unless you use a larger framebuffer. Though of course the OSD used to scale to low res fine before.

**Comment by r-type** [comment] 2016-10-29 21:46
This is the first try to fix the aspet issue in current libretro-mame ,difference I can see between my fork and here it's that view is not explicitly define in the Libretro OSD part.
So i set the view to pixel aspect after computing retro_aspect (with compute_visible_area) .
not sure if it ll work fine .

**Comment by Awakened0** [comment] 2016-10-30 03:19
I grabbed the latest build from the buildbot and both aspect ratios are working correctly now with the non-alternate renderer. The unevenstretch missing pixel problem is fixed too :D

**Comment by Tatsuya79** [comment] 2016-10-30 09:35
Not sure if that can help.
I tried to put "uifont something.tff " (font in retroarch folder) in mame.ini.
It displays the in-game gui on the whole screen but empty of any font.

Could it be just a font issue and not a GUI resolution problem?

**Comment by Tatsuya79** [comment] 2016-10-30 09:46
Forget it, just tried an X68000 game that is 768x512 and I can read the GUI.
But the X68000 "Dos Screen" has those stretched/missing pixels and the emulation is awfully slower than usual.
http://postimg.org/image/xn7kobcer/

**Comment by r-type** [comment] 2016-10-30 10:12
You mean with 0.174 not my fork ?  Because it should not be slower slower with this repo ,the fix only change view not résolution .

**Comment by Tatsuya79** [comment] 2016-10-30 11:19
Yes, 0.174 from this GIT.

Just tried again with your fork above and that's good: speed and resolution in X68000.
It's completely restarting Retroarch display at each resolution change though, wouldn't set_geometry be better?
The in-game GUI is half its size compared to the older 0.170 version.

**Comment by r-type** [comment] 2016-10-30 11:53
For x68000 res , i have tested with fresh config (NO mame ini/cfg/nvram ect...)
and after swapping to no led layout ,  what i get:

![aku](https://cloud.githubusercontent.com/assets/3614417/19836388/9f3ff3ca-9e9f-11e6-8fef-ed13f7ce6b9c.png)

i don't understand the speed loose with the fix for 0.174, as it only change view. have to investigate and see if the is no other problem with the fix.
I also have to find/grab a previous 0.172 to see how it was before. 

For 0.179 it's a rough port , so have to see for resolution change and all the missing stuff...

**Comment by twinaphex** [comment] 2016-10-30 11:55
Hi there r-type, thanks again for looking into the libretro port and fixing the brokenness of the graphics.

When you feel the time is right, feel free to upgrade the repo to your fork, we really need somebody who has expertise with MAME so that we can keep the port continually updated.

**Comment by Tatsuya79** [comment] 2016-10-30 12:27
I'm always comparing vs the last version from the buildbot without all the OSD issues that I kept:
[170 for windows x64.](https://mega.nz/#!FlU20RTK!yD-giErYYRDfj3eDfLga8Q549nFtLIproH34CxgqYdo)

So the loss in speed could have happened in-between.

**Comment by r-type** [comment] 2016-10-30 13:26
Ok thanks provied 0.170 i ll check.
Also thanks for the osd size tips. I ll check that maybe we can fix font.

For the speed is 0.174 without the fix is slower than with the aspect view fix ? 
If not
I thinks squarepusher is right.newer versions are generally slower. But if 0.179 is faster than 0.174 there must be a mystake somewhere.

Squarepusher, yes i will try to fix and clean up the pb with 0.179 fork. Then we can rebase here.

**Comment by Tatsuya79** [comment] 2016-10-30 13:55
I don't have the previous 0.174 from yesterday to test.

But it's probably not a Mame regression: I don't see anything about it on MameTesters site and stand-alone 0.179 + R-type fork are OK speed wise.

**Comment by Tatsuya79** [comment] 2016-10-30 13:57
> This branch is 666 commits ahead, 6 commits behind twinaphex:master. 

That's probably what's going on: it's possessed, right in time for Halloween.

**Comment by r-type** [comment] 2016-10-30 17:40
I have test the 3 libretro mame windows version (170/174/179)  with x68000 drv , using wine.

Speed problem:
Yes there is a speed problem with 0.174 using x68000 (but i didn't notice speed problem with 0.174 linux version from my own build).
wine work at normal speed with 170 & 179 , but nearly freeze with 174 (having 1fps).
not sure why.

Aspect/view pb:
all the 3 start with ChangeAV: w:814 h:512 ra:1.412429.
at least there are problem aspect/view with x68000 layout, the view with drives led a completely
broken ( diagonal, wrong size/pitch ?)

179 have some switching res like state before , that play on the aspect 
start with ChangeAV: w:814 h:512 ra:1.412429.
then ChangeAV: w:543 h:512 ra:1.412429.
later  ChangeAV: w:271 h:257 ra:1.412429.
maybe have to prohibit the switching.

174 (linux as x68000 unasable on windows ) not having  proper aspect in game.
i thinks at least there is something with the view ,  sfa2 only have 3 view (standard 4/3 , pixel aspect , and cocktail ) and aspect is fine. x68000 have drive led layout in addition and aspect is broken.

**Comment by r-type** [comment] 2016-11-01 16:18
Ok second try for 0.174 aspect , 
i use a pixel_aspect
```
 pix_asp=cur_asp/(float)((float)fb_width/(float)fb_height);
```
 cur_asp is aspect of the current view.
and finally i set the bound with  
```
 our_target->set_bounds(fb_width, fb_height,pix_asp);
```

OSD font look is always broken as pix_aspect apply also to OSD font ,but in-game aspect look fine for me.

Tatsuya79 and Awakened0 if you could try it to see if aspect is correct for you and there is no regression ?

http://dl.free.fr/g8HvtciLs

**Comment by Awakened0** [comment] 2016-11-01 19:13
I tested sfa2u and 1943 and both work fine with both aspect ratios. I also tried wbml and wbmlvc and that game freezes on the initializing screen for some reason. The log says:

> RetroArch [libretro INFO] :: ChangeAV: w:512 h:224 ra:1.333333.
> Ignoring MAME exception: install_write_handler: In range c000-c003 mask 0 mirror 1fff select 0, mirror touches a changing address bit, did you mean 1ffc ?
> 
> Fatal error: install_write_handler: In range c000-c003 mask 0 mirror 1fff select 0, mirror touches a changing address bit, did you mean 1ffc ?
> 
> RetroArch [libretro INFO] :: OSD exit called
> RetroArch [libretro ERROR] :: Running a dead emulator.

Full log here: http://pastebin.com/CGeugWV0

**Comment by Tatsuya79** [comment] 2016-11-01 21:21
Yes wbml gives me that same error.

The ratio looks alright at first but you can't use Mame video settings now.
If you rotate or use "ror 1" in an ini for a vertical game the result is quite strange.

Going into Mame GUI video options and changing from 4:3 to Pixel Aspect only changes the OSD scaling. (see akumajou on x6800 or '88 Games)
But this wasn't doing anything at all in 0.170.

**Comment by zerojay** [comment] 2016-11-06 21:30
@twinaphex There's a definite speed issue in the current MAME core in libretro. I was hardcore busy for a few months and didn't touch my gaming pc for a while, updated Retroarch and all cores and was quite shocked to see that my rig no longer ran Blitz at 60fps through RA. I thought, like you, that it was MAME just getting more accurate and losing speed over time, but upon downloading the latest standalone MAME, I could see that it appeared to be an RA rendering problem. Blitz was only running at about 50% speed and you could even see the RA interface was struggling the slightest bit even without cores loaded. Standalone MAME is back to the speeds I was getting and expecting with Blitz back to 100% without a sweat.

**Comment by twinaphex** [comment] 2016-11-06 21:39
@zerojay We will need core contributors then to bring mainline MAME core up to the standards of the other cores.

**Comment by twinaphex** [comment] 2016-11-06 21:43
@r-type Can we resync your repo with this one? Is yours based on the latest 0.179 code, and is it better than what we currently have?

**Comment by fr500** [comment] 2016-11-06 22:15
@zerojay that sounds like an issue on your end if the gui is struggling.
It happens every now and then with NVIDIA drivers, you just have to set the power profile to maximum performance so it doesn't clock down.

**Comment by Enverex** [comment] 2016-11-07 11:05
@r-type : Don't worry if the nagscreen patch doesn't apply cleanly. Leave it out and I'll re-do it manually once you've merged your branch back in.

**Comment by r-type** [comment] 2016-11-07 22:51
@twinaphex @Enverex  i will re-sync soon (in few days) , 
for now I have some other things to finish and I've to clean-up code before.
but I ll try do it this week end.

@fr500 @zerojay  not sure it's a GPU issue , maybe toolchain or libco issue.
when i try the windows libretro mame nightly build ,
with nfl blitz the game is really slow , near 7fps in title screen (same like i report for x68000 previously)
but if i compile myself and tweak libco for using fiber instead of amd64 ,
the speed is normal and full fps at title screen.

**Comment by fr500** [comment] 2016-11-07 23:07
using fiber on a mingw build is just a hack though..
It's not likely gonna be stable.

Maybe it's using the SJLJ backend, it should use the x86_64 backend.
But I don't see why libco would make a huge impact here, there is only one context switch per-frame, it's nothing like bsnes switching 10000times per-frame

**Comment by twinaphex** [comment] 2016-11-07 23:54
Ideally we get rid of libco at some point in time, hopefully with the new MAME internals it should be possible to do that.

**Comment by r-type** [comment] 2016-11-08 12:19
@fr500 
you allready know all these things, we debate about it  years ago :) 
it's not libco but SEH vs SJLJ exception model , and the only way to deal with SEH TC with libco is to use fiber instead of amd64 backend.

**Comment by RetroUp** [comment] 2016-11-11 23:05
http://mrdo.mameworld.info/mame_artwork_supp.php

Adding ui.bdf to the root RA dir helps. Not perfect but it is readable. A wide font like Galaxian is best.

Default is named ui.bdf. You can change name and path from CLI with "-uifont"

**Comment by fr500** [comment] 2016-11-11 23:21
@r-type indeed removing libco and iterating per-frame would be nicer.

**Comment by r-type** [comment] 2016-11-12 09:47
@fr500 yeah , remove libco can be done (i did it for 2014 )

but I'm not agree with removing the OSD part, mame have many  options and  it will be waste of time to recreate all them in core option. another thing it's for now in core option don't allow file browsing ect //, that is a big lack for my part ,eg you can't mount new media on mess machine...

That said it's my point of view you are free to implement the core better like you describe here,
but for my part I will stay with the mame built-in osd.

Now regarding the aspect , a lack of libretro is that core can't guess monitor aspect and resolution supported , so it can't setup properly an alternate renderer like the official does.

**Comment by r-type** [comment] 2016-11-12 16:51
@fr500  POC of removing libco here https://github.com/r-type/mame
still WIP and maybe unsafe ,i built with a SEH mingw64TC .

http://dl.free.fr/qLenbEvdq

feedback are welcome ,to see regression without libco.

**Comment by fr500** [comment] 2016-11-12 17:04
Thanks @r-type gonna give it a shot

**Comment by twinaphex** [comment] 2016-11-12 17:10
Thanks for this @r-type, but can you rebase against latest MAME ?

**Comment by r-type** [comment] 2016-11-12 17:27
@twinaphex  yes I will but I need more time also i had to play with my repositories to be able to fork this one. and then loose upstream for  0.179. I need to redone it. maybe in a few days I hope.

**Comment by r-type** [comment] 2016-11-12 18:03
@twinaphex  can you move this one to another name and rebase from mamdev  at this commit
https://github.com/mamedev/mame/tree/0d87ff49b17df9995d4556aaea9c5680b446604f ?
i will  then patch wth my previous commit.

**Comment by twinaphex** [comment] 2016-11-12 19:04
@r-type OK.

**Comment by twinaphex** [comment] 2016-11-12 19:07
@r-type Done, this is the new repo - 

https://github.com/libretro/mame

And I gave you admin access to it.

**Comment by r-type** [comment] 2016-11-12 19:14
thanks , I' ll push later.

**Comment by r-type** [comment] 2016-11-13 14:02
@RetroUp  thanks for the tips that solve the font rendering problem!
in the root of the repository there is a font named uismall.bdf if using it then the UI look as before.

As RetroUp said, you have 3 ways to use it .
- rename it to ui.bdf and put it in the retroarch folder
- using option uifont in your mame.ini , replace "uifont  default" with  "uifont /path_to_font/uismall.bdf" 
- using CLI and adding "-uifont /path_to_font/uismall.bdf"

**Comment by Awakened0** [comment] 2016-11-13 19:44
Any way that can be baked into the core and used by default? Or at least changed to look for it inside the System folder by default?

**Closed** 2021-11-26 02:50 UTC
